#REDES SOCIALES
FACEBOOK = "https://www.facebook.com/arsenaldeodio"
INSTAGRAM = "https://www.instagram.com/arsenaldeodiooficial/"
BANDCAMP = "https://arsenaldeodio.bandcamp.com/album/muerte-en-el-mosh"

# PLATAFORMAS 
SPOTIFY = "https://open.spotify.com/intl-es/album/4sk89SFlS5mj7lapuRBWhZ"

# INTEGRANTES - FACEBOOK
GUITARRISTA_PRINCIPAL_FACEBOOK = "https://www.facebook.com/emersonmustain.guevara"
VOCALISTA_FACEBOOK = "https://www.facebook.com/tom.arayadias"
BAJISTA_FACEBOOK = "https://www.facebook.com/saady.rueda"
BATERISTA_FACEBOOK = ""
GUITARRISTA_SECUNDARIO_FACEBOOK = ""

# INTEGRANTES - INSTAGRAM
GUITARRISTA_PRINCIPAL_FACEBOOK = ""
VOCALISTA_FACEBOOK = ""
BAJISTA_FACEBOOK = ""
BATERISTA_FACEBOOK = ""
GUITARRISTA_SECUNDARIO_FACEBOOK = ""

# INTEGRANTES - TWITTER
GUITARRISTA_PRINCIPAL_FACEBOOK = ""
VOCALISTA_FACEBOOK = ""
BAJISTA_FACEBOOK = ""
BATERISTA_FACEBOOK = ""
GUITARRISTA_SECUNDARIO_FACEBOOK = ""

# INTEGRANTES - YOUTUBE
GUITARRISTA_PRINCIPAL_FACEBOOK = ""
VOCALISTA_FACEBOOK = ""
BAJISTA_FACEBOOK = ""
BATERISTA_FACEBOOK = ""
GUITARRISTA_SECUNDARIO_FACEBOOK = ""

# INTEGRANTES - TIKTOK
GUITARRISTA_PRINCIPAL_FACEBOOK = ""
VOCALISTA_FACEBOOK = ""
BAJISTA_FACEBOOK = ""
BATERISTA_FACEBOOK = ""
GUITARRISTA_SECUNDARIO_FACEBOOK = ""


